SHOW TABLES ;

CREATE OR ALTER TABLE test2 (
    COLUMN1 VARCHAR
);

DESCRIBE TABLE test2;
select * from test2;
CREATE OR ALTER TABLE test2
(
    COLUMN1 VARCHAR,
    COLUMN2 VARCHAR,
    Column3 VARCHAR
);