


USE ROLE ACCOUNTADMIN ;

USE WAREHOUSE IBHTEST_WH ;

USE SCHEMA IBHTEST_DB.DEV_TEST;

CREATE OR REPLACE SECRET IBH_SECRET
    TYPE = PASSWORD
    USERNAME = $GITHUBUSERNAME
    PASSWORD = $GITHUBTOKEN;

SHOW SECRETS;
DESCRIBE SECRET IBH_SECRET ;

CREATE OR REPLACE API INTEGRATION IBH_API_INTEGRATION
    API_PROVIDER = GIT_HTTPS_API
    API_ALLOWED_PREFIXES = ('https://github.com/imenebh2611')
    ALLOWED_AUTHENTICATION_SECRETS = (IBH_SECRET)
    ENABLED = TRUE;

SHOW API INTEGRATIONS;
DESCRIBE API INTEGRATION IBH_API_INTEGRATION ;


CREATE OR REPLACE GIT REPOSITORY IBH_REPO
    API_INTEGRATION = IBH_API_INTEGRATION
    GIT_CREDENTIALS = IBH_SECRET
    ORIGIN = 'https://github.com/imenebh2611/demo-change.git' ;

DESCRIBE GIT REPOSITORY IBH_REPO;

LIST @IBH_REPO/branches/main;
LIST @IBH_REPO/tags/tag_name;
LIST @IBH_REPO/commits/commit_hash;

SHOW GIT BRANCHES IN IBH_REPO;

ALTER GIT REPOSITORY IBH_REPO FETCH;